"""Browser-based compatibility client for user-triggered browser flows.

stoken can be generated by the browser's JS environment when a user-initiated
login flow needs compatibility help. Low-Risk Assistance Mode blocks sensitive
automation such as outreach, bulk actions, risk-control retries, and candidate
personal-data workflows before they reach this client.

Supports two modes:
  1. CDP mode: connects to user's existing Chrome via DevTools Protocol
  2. Patchright mode (fallback): launches a headless Chromium instance
"""
import asyncio
import sys
import time
from collections.abc import Callable
from pathlib import Path
from types import TracebackType
from typing import Any, TypeVar, cast

from patchright.sync_api import sync_playwright

from urllib.parse import urlencode

from pet_boss.api import endpoints
from pet_boss.api.throttle import RequestThrottle
from pet_boss.auth.browser import _DEFAULT_CDP_URL as CDP_DEFAULT_URL
from pet_boss.auth.browser import HOME_URL, _STOKEN_GENERATION_WAIT, _extract_stoken, probe_cdp

HOME_URL = "https://www.zhipin.com/"
_NAV_OPEN_TIMEOUT_MS = 60_000
_DETACHED_VIEWERS: list[tuple[Any, Any]] = []

_BROWSER_LOST_HINTS = (
	"target closed",
	"browser has been closed",
	"context or browser",
	"session closed",
	"connection closed",
	"page crashed",
	"browser closed",
	"target page, context or browser has been closed",
)

_T = TypeVar("_T")


def _on_running_asyncio_loop() -> bool:
	try:
		return asyncio.get_running_loop().is_running()
	except RuntimeError:
		return False


def _run_browser_thread_safe(func: Callable[[], _T]) -> _T:
	"""patchright 同步 API 不可在 asyncio 事件循环线程调用。"""
	if _on_running_asyncio_loop():
		from pet_boss.web.browser_executor import run_browser_blocking

		return run_browser_blocking(func)
	return func()


def is_browser_session_lost_message(message: str) -> bool:
	"""判断异常/返回信息是否像自动化 Chromium 已断开（先崩窗后卡）。"""
	msg = (message or "").lower()
	return any(hint in msg for hint in _BROWSER_LOST_HINTS)


def is_browser_session_lost_exception(exc: BaseException) -> bool:
	if type(exc).__module__ == "greenlet" and type(exc).__name__ == "error":
		return True
	return is_browser_session_lost_message(str(exc))


def build_job_detail_page_url(job_id: str, security_id: str = "") -> str:
	"""构建 BOSS 岗位详情页 URL（可选附带 securityId）。"""
	job_id = str(job_id or "").strip()
	if not job_id:
		raise ValueError("job_id 不能为空")
	base = f"{endpoints.BASE_URL}/job_detail/{job_id}.html"
	security_id = str(security_id or "").strip()
	if security_id:
		return f"{base}?{urlencode({'securityId': security_id})}"
	return base


def open_zhipin_job_page(
	url: str,
	*,
	cookies: dict[str, Any],
	user_agent: str = "",
	cdp_url: str | None = None,
	logger: Any = None,
) -> dict[str, Any]:
	"""在带登录态的浏览器中打开 BOSS 页面（避免系统默认浏览器重复登录）。"""
	url = str(url or "").strip()
	if not url:
		raise ValueError("url 不能为空")

	def _log(msg: str) -> None:
		if logger is not None and hasattr(logger, "info"):
			logger.info(msg)

	if probe_cdp(cdp_url):
		try:
			if _open_job_page_via_cdp(url, cookies=cookies, cdp_url=cdp_url, user_agent=user_agent):
				_log(f"[boss] 已在 Chrome 新标签页打开: {url}")
				return {"mode": "cdp", "url": url, "message": "已在 Chrome 新标签页打开岗位详情"}
		except Exception as exc:
			_log(f"[boss] CDP 打开岗位页失败（{exc}），改用登录态浏览器")

	pw = _run_browser_thread_safe(lambda: sync_playwright().start())
	browser = pw.chromium.launch(headless=False)
	context = browser.new_context(
		user_agent=user_agent or None,
		viewport={"width": 1280, "height": 800},
		locale="zh-CN",
		timezone_id="Asia/Shanghai",
	)
	context.add_cookies([
		{"name": name, "value": str(value), "domain": ".zhipin.com", "path": "/"}
		for name, value in cookies.items()
	])
	page = context.new_page()
	try:
		page.goto(url, wait_until="domcontentloaded", timeout=_NAV_OPEN_TIMEOUT_MS)
	except Exception as exc:
		_log(f"[boss] 打开岗位页导航: {exc}")
	_DETACHED_VIEWERS.append((pw, browser))
	_log(f"[boss] 已用登录态浏览器打开: {url}")
	return {"mode": "browser", "url": url, "message": "已用登录态打开岗位详情"}


def _open_job_page_via_cdp(
	url: str,
	*,
	cookies: dict[str, Any],
	cdp_url: str | None,
	user_agent: str,
) -> bool:
	"""在 CDP Chrome 新标签页打开 URL，必要时注入 session cookies。"""
	base = cdp_url or CDP_DEFAULT_URL
	ws_url = probe_cdp(cdp_url)
	if not ws_url:
		return False
	pw = _run_browser_thread_safe(lambda: sync_playwright().start())
	browser = pw.chromium.connect_over_cdp(base)
	context = browser.contexts[0] if browser.contexts else browser.new_context()
	existing = {
		c["name"]: c["value"]
		for c in context.cookies()
		if "zhipin.com" in c.get("domain", "")
	}
	if not existing.get("wt2") and cookies.get("wt2"):
		context.add_cookies([
			{"name": name, "value": str(value), "domain": ".zhipin.com", "path": "/"}
			for name, value in cookies.items()
		])
	elif not existing.get("wt2"):
		pw.stop()
		return False
	page = context.new_page()
	if user_agent:
		try:
			page.set_extra_http_headers({"User-Agent": user_agent})
		except Exception:
			pass
	try:
		page.goto(url, wait_until="domcontentloaded", timeout=_NAV_OPEN_TIMEOUT_MS)
	except Exception:
		pass
	_DETACHED_VIEWERS.append((pw, browser))
	return True


# 超时常量
_CDP_PROBE_TIMEOUT = 3           # CDP 探测 HTTP 超时（秒）
_NAV_TIMEOUT_MS = 15000          # 页面导航超时（毫秒）
_HEADLESS_NETWORKIDLE_GRACE_MS = 3000  # headless 预热的额外宽限，避免卡满 30s

# macOS / Linux / Windows Chrome user data 默认路径
_CHROME_USER_DATA_CANDIDATES = [
	Path.home() / "Library/Application Support/Google/Chrome",              # macOS
	Path.home() / ".config/google-chrome",                                  # Linux
	Path.home() / "AppData/Local/Google/Chrome/User Data",                  # Windows
]


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch).

	Tries CDP connection to user's Chrome first; falls back to headless patchright.
	"""

	def __init__(self, cookies: dict[str, Any], user_agent: str, *, delay: tuple[float, float] = (1.5, 3.0), cdp_url: str | None = None, logger: Any = None) -> None:
		self._throttle = RequestThrottle(delay)
		# patchright 运行时创建；注解为 Any 让 mypy 对外部依赖放行
		self._pw: Any = None
		self._browser: Any = None
		self._context: Any = None
		self._page: Any = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False
		self._cdp_url = cdp_url
		self._is_cdp = False
		self._own_context = False  # 是否由我们创建的 context（需要在 close 时清理）
		self._logger = logger

	def _log(self, message: str) -> None:
		"""通过注入的 logger 输出，受 --log-level 控制。"""
		if self._logger:
			self._logger.info(message)
		else:
			print(message, file=sys.stderr)

	def _ensure_started(self) -> None:
		if self._started:
			return
		if _on_running_asyncio_loop():
			_run_browser_thread_safe(self._ensure_started)
			return

		self._pw = sync_playwright().start()
		self._start_headless()

	def _try_cdp(self) -> bool:
		"""Try connecting to user's Chrome via CDP.

		Attempts in order:
		  1. Explicit cdp_url if provided
		  2. Default http://localhost:9222 (+ auto WS fallback)
		  3. WebSocket URL from Chrome's DevToolsActivePort file
		"""
		urls_to_try = []
		if self._cdp_url:
			urls_to_try.append(self._cdp_url)
		urls_to_try.append(CDP_DEFAULT_URL)

		# 从 DevToolsActivePort 文件读取 WebSocket URL
		ws_url = self._read_devtools_active_port()
		if ws_url:
			urls_to_try.append(ws_url)

		for url in urls_to_try:
			if self._try_connect(url):
				return True
			# HTTP URL 连接失败时，尝试从 /json/version 获取 WS URL
			if url.startswith("http"):
				ws = self._fetch_ws_url(url)
				if ws and self._try_connect(ws):
					return True
		return False

	def _try_connect(self, url: str) -> bool:
		"""Attempt a single CDP connection, reusing user's existing context.

		Reuses the first existing browser context to preserve the user's
		login state and avoid creating extra browser state. Only creates a
		new context when none exists.
		"""
		try:
			self._browser = self._pw.chromium.connect_over_cdp(url)
			contexts = self._browser.contexts

			if contexts:
				# 复用用户现有 context（保留登录态，避免额外浏览器状态）
				self._context = contexts[0]
				self._own_context = False  # 非我们创建，close 时不关闭
			else:
				# 没有已存在 context，创建新的并注入 cookies
				self._context = self._browser.new_context()
				if self._cookies:
					self._context.add_cookies([
						{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
						for name, value in self._cookies.items()
					])
				self._own_context = True

			self._page = self._context.new_page()
			# CDP 模式下用较长超时 + commit 级等待（避免 networkidle 卡住）
			try:
				self._page.goto(HOME_URL, wait_until="commit", timeout=_NAV_TIMEOUT_MS)
			except Exception:
				pass  # 即使导航超时，页面 JS 环境已可用
			self._started = True
			self._is_cdp = True
			reuse_label = "复用用户 context" if not self._own_context else "新建 context"
			self._log(f"[boss] CDP 连接成功 ({url})，{reuse_label}")
			return True
		except Exception:
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
				self._browser = None
			return False

	@staticmethod
	def _fetch_ws_url(http_url: str) -> str | None:
		"""Fetch WebSocket debugger URL from Chrome's /json/version endpoint."""
		import httpx
		try:
			resp = httpx.get(f"{http_url}/json/version", timeout=_CDP_PROBE_TIMEOUT)
			payload = resp.json()
			if not isinstance(payload, dict):
				return None
			return cast("str | None", payload.get("webSocketDebuggerUrl"))
		except (httpx.HTTPError, ValueError, KeyError):
			return None

	@staticmethod
	def _read_devtools_active_port() -> str | None:
		"""Read Chrome's DevToolsActivePort file to get WS endpoint."""
		for user_data_dir in _CHROME_USER_DATA_CANDIDATES:
			port_file = user_data_dir / "DevToolsActivePort"
			if port_file.exists():
				try:
					lines = port_file.read_text().strip().splitlines()
					if len(lines) >= 2:
						port = lines[0].strip()
						ws_path = lines[1].strip()
						return f"ws://127.0.0.1:{port}{ws_path}"
				except Exception:
					continue
		return None

	def _start_headless(self) -> None:
		"""Fallback: launch headless patchright Chromium."""
		self._browser = self._pw.chromium.launch(headless=False)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._own_context = True
		self._context.add_cookies([
			{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
			for name, value in self._cookies.items()
		])
		self._page = self._context.new_page()
		self._page.goto(endpoints.WEB_GEEK_JOB_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		try:
			self._page.wait_for_load_state("networkidle", timeout=_HEADLESS_NETWORKIDLE_GRACE_MS)
		except Exception as e:
			# zhipin 首页常驻请求较多，headless 模式下不一定能进入 networkidle；
			# 页面 JS 环境已可用时，继续直接发起 fetch 请求更稳。
			self._log(f"[boss] headless 首页未进入 networkidle（{e}），继续直接发起请求")
		self._started = True
		self._is_cdp = False
		self._log("[boss] CDP 不可用（提示：需以 --remote-debugging-port=9222 启动 Chrome），降级到 headless patchright")

	def refresh_home_for_new_round(self) -> None:
		"""回到 BOSS 首页刷新并重新进入职位列表，模拟新一轮独立浏览。"""
		self._ensure_started()
		if not self._page:
			return
		self._page.goto(HOME_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		self._page.reload(wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		self._page.goto(endpoints.WEB_GEEK_JOB_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		try:
			self._page.wait_for_load_state("networkidle", timeout=_HEADLESS_NETWORKIDLE_GRACE_MS)
		except Exception:
			pass

	def focus_window(self, *, url: str | None = None) -> bool:
		"""聚焦自动化 Chromium/CDP 窗口（Web 搜岗登录态在此，勿弹系统默认浏览器）。"""
		self._ensure_started()
		if not self._page:
			return False
		try:
			if url:
				self._page.goto(url, wait_until="commit", timeout=_NAV_TIMEOUT_MS)
			self._page.bring_to_front()
			mode = "cdp" if self._is_cdp else "patchright"
			self._log(f"[boss-browser] 已聚焦自动化窗口（{mode}）")
			return True
		except Exception as exc:
			self._log(f"[boss-browser] 聚焦自动化窗口失败：{exc}")
			return False

	def restart_session(self) -> dict[str, Any]:
		"""关闭当前浏览器页面/实例并重建，用于导航卡死恢复。"""
		mode = "cdp" if self._is_cdp else "patchright"
		outcome: dict[str, Any] = {
			"ok": False,
			"mode": mode,
			"phase": "begin",
			"sequence": "stall_then_close",
			"close_ok": False,
			"launch_ok": False,
			"error": "",
		}
		self._log(f"[boss-browser] 重启开始（先卡后关）：mode={mode}，正在关闭旧窗口…")
		try:
			if self._is_cdp:
				self._restart_cdp_page()
				outcome["close_ok"] = True
				outcome["launch_ok"] = bool(self._page and self._started)
				outcome["phase"] = "ready" if outcome["launch_ok"] else "launch_failed"
				outcome["ok"] = outcome["launch_ok"]
				if outcome["ok"]:
					self._log("[boss-browser] CDP 页面重启完成，新标签已就绪")
				else:
					outcome["error"] = "CDP 页面重启后未就绪"
					self._log(f"[boss-browser] 重启失败：{outcome['error']}")
				return outcome

			self._teardown_headless(keep_playwright=True)
			outcome["close_ok"] = True
			outcome["phase"] = "closed"
			self._log("[boss-browser] 旧 Chromium 窗口已关闭，正在拉起新窗口…")
			if self._pw is None:
				self._pw = _run_browser_thread_safe(lambda: sync_playwright().start())
			self._start_headless()
			outcome["launch_ok"] = bool(self._page and self._browser and self._started)
			outcome["phase"] = "ready" if outcome["launch_ok"] else "launch_failed"
			outcome["ok"] = outcome["launch_ok"]
			if outcome["ok"]:
				self._log("[boss-browser] 新 Chromium 窗口已拉起并就绪")
			else:
				outcome["error"] = "Chromium 启动后页面未就绪"
				self._log(f"[boss-browser] 新窗口拉起失败：{outcome['error']}")
		except Exception as exc:
			outcome["phase"] = "failed"
			outcome["error"] = str(exc) or exc.__class__.__name__
			self._log(f"[boss-browser] 重启异常（phase={outcome.get('phase')}）：{outcome['error']}")
		return outcome

	def _teardown_headless(self, *, keep_playwright: bool = False) -> None:
		if self._page:
			try:
				self._page.close()
			except Exception:
				pass
			self._page = None
		if self._context:
			try:
				self._context.close()
			except Exception:
				pass
			self._context = None
		if self._browser:
			try:
				self._browser.close()
			except Exception:
				pass
			self._browser = None
		if not keep_playwright and self._pw:
			try:
				self._pw.stop()
			except Exception:
				pass
			self._pw = None
		self._started = False

	def _restart_cdp_page(self) -> None:
		if self._page:
			try:
				self._page.close()
			except Exception:
				pass
			self._page = None
		if not self._context:
			self._started = False
			self._ensure_started()
			return
		self._page = self._context.new_page()
		try:
			self._page.goto(
				endpoints.WEB_GEEK_JOB_URL,
				wait_until="commit",
				timeout=_NAV_TIMEOUT_MS,
			)
		except Exception as exc:
			self._log(f"[boss] CDP 重启后导航: {exc}")
		self._started = True
		self._log("[boss] CDP 页面已重启")

	def apply_stoken(self, stoken: str) -> None:
		"""将刷新后的 stoken 写入浏览器 Cookie，供 fetch(credentials:include) 使用。"""
		if not stoken:
			return
		self._cookies["__zp_stoken__"] = stoken
		if not self._started or not self._context:
			return
		cookie = {
			"name": "__zp_stoken__",
			"value": stoken,
			"domain": ".zhipin.com",
			"path": "/",
		}
		try:
			self._context.add_cookies([cookie])
		except Exception as exc:
			self._log(f"[boss] 写入 stoken cookie 失败: {exc}")
		if self._page:
			try:
				self._page.evaluate(
					"""(stoken) => {
						document.cookie = '__zp_stoken__=' + stoken + '; domain=.zhipin.com; path=/';
						window.__zp_stoken__ = stoken;
					}""",
					stoken,
				)
			except Exception as exc:
				self._log(f"[boss] 页面注入 stoken 失败: {exc}")

	def refresh_stoken_in_page(self) -> str:
		"""在当前浏览器会话内刷新 stoken（不另开 patchright，避免与搜岗会话冲突）。"""
		self._ensure_started()
		if not self._page:
			raise RuntimeError("浏览器页面未就绪，无法刷新 stoken")
		self._log("[boss] 搜岗批次刷新：访问首页以生成新 stoken…")
		try:
			self._page.goto(HOME_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		except Exception as exc:
			self._log(f"[boss] 刷新 stoken 时首页导航异常（继续尝试读取）: {exc}")
		time.sleep(_STOKEN_GENERATION_WAIT)
		stoken = _extract_stoken(self._page)
		if not stoken:
			raise RuntimeError("浏览器页面未生成 stoken")
		self.apply_stoken(stoken)
		self._log("[boss] stoken 已在当前浏览器会话内刷新")
		return stoken

	# ── Core request via browser fetch() ─────────────────────────────

	def request(self, method: str, url: str, *, params: dict[str, Any] | None = None, data: dict[str, Any] | None = None) -> dict[str, Any]:
		self._ensure_started()
		self._throttle.wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		# Playwright 模式（CDP 或 headless）
		try:
			result = self._page.evaluate("""
			async ({method, url, params, data, referer}) => {
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'Referer': referer,
							'X-Requested-With': 'XMLHttpRequest',
						},
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					return {code: -1, message: e.message, zpData: {}};
				}
			}
		""", {"method": method, "url": url, "params": params or {}, "data": data, "referer": referer})
		except Exception as exc:
			if is_browser_session_lost_exception(exc):
				msg = str(exc) or "浏览器会话已断开"
				self._log(f"[boss-browser] 会话失效（先崩窗后卡？）：{msg}")
				return {"code": -2, "message": msg, "browser_lost": True, "zpData": {}}
			raise

		if isinstance(result, dict):
			msg = str(result.get("message") or "")
			if result.get("code") == -1 and is_browser_session_lost_message(msg):
				self._log(f"[boss-browser] fetch 返回会话失效（先崩窗后卡？）：{msg}")
				result = {**result, "code": -2, "browser_lost": True}

		self._throttle.mark()
		return cast("dict[str, Any]", result)

	# ── Lifecycle ────────────────────────────────────────────────────

	@property
	def is_cdp(self) -> bool:
		"""Whether this session is using CDP connection to user's Chrome."""
		return self._is_cdp

	def close(self) -> None:
		if self._is_cdp:
			# CDP 模式：关闭我们创建的 page 和 context，不关闭用户浏览器
			if self._page:
				self._safe_close(self._page.close)
			if self._own_context and self._context:
				self._safe_close(self._context.close)
		else:
			# Headless 模式：关闭整个浏览器实例
			if self._browser:
				self._safe_close(self._browser.close)
		if self._pw:
			self._safe_close(self._pw.stop)
		self._started = False

	@staticmethod
	def _safe_close(close_fn) -> None:
		try:
			close_fn()
		except Exception as exc:
			# patchright 在页面已关闭或线程切换时可能抛 greenlet.error，搜岗结束时可忽略
			if type(exc).__module__ == "greenlet" and type(exc).__name__ == "error":
				return

	def __enter__(self) -> "BrowserSession":
		return self

	def __exit__(
		self,
		exc_type: type[BaseException] | None,
		exc_val: BaseException | None,
		exc_tb: TracebackType | None,
	) -> None:
		self.close()
